server:
  port: 8881

spring:
  application:
    name: sts-auth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/yc-sts-db-auth?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: yc-sts-db-auth
    password: yc-sts-db-auth
  messages:
    basename: classpath*:i18n/messages
    use-code-as-default-message: true
    encoding: UTF-8
    cache-duration: 3600
    fallback-to-system-locale: false

mybatis-plus:
  mapper-locations: classpath*:mappers/*.xml
  global-config:
    db-config:
      # 逻辑删除配置删除前
      logic-not-delete-value: 0
      # 逻辑删除配置删除后
      logic-delete-value: 1
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
  config: classpath:config/logback-spring.xml
  level:
    com.yaocode.sts.auth: INFO
    org.springframework: INFO
    org.apache.ibatis: debug
  file:
    path: ./logs

yaocode:
  database:
    migrate:
      sqlScriptPath:
        - classpath*:/db/migration/mysql/*.sql
#  web:
#    api:
#      elapsed:
#        enabled: false
